### ISSUE TITLE
send status to api

### ISSUE THREAD

**Issue by silvioheinze** [luftdaten-at/firmware#36]
Send status like errors or successful updates to api endpoint /station/status

**Comment by silvioheinze** [comment]
status:

- station_id
- time
- level (info, debug, error)
- message

**Comment by n11ik** [comment]
Steps
* find or create logging library
* implement and test logging within the upgrade process

**Comment by n11ik** [comment]
I created a simple logging class and replaced all print statements with logging.[log level].
TODO
* send status to API, waiting for https://github.com/luftdaten-at/luftdaten-api/issues/5, to be implemented
