### ISSUE TITLE
add firmware self-upgrade for wifi-connected devices

### ISSUE THREAD

**Issue by silvioheinze** [luftdaten-at/firmware#5]
daily check whether there is a new firmware version (place not clear yet, perhaps here on GitHub?). If found, then download and install.

**Comment by silvioheinze** [comment]
@n11ik  Funktioniert diese Implementation für den ESP32-S3?
https://github.com/LionCave97/CircuitPython-OTA

**Comment by silvioheinze** [comment]
Update-Server: https://github.com/luftdaten-at/luftdaten-update

**Comment by n11ik** [comment]
TODO:
- rollback
- check if it is possible to auto reload the device when an exception occurs
